.TH THPTX 1 "November 2025" "THPT Documentation"
.SH NAME
THPTx \- Verschachteltes Webprojektmodul im THPT-Repository
.SH SYNOPSIS
.B thptx
.SH DESCRIPTION
THPTx ist ein modularer Bestandteil des THPT-Repositories. Es enthält indexierte HTML-Seiten, Subsites und thematische Inhalte, die über eine dynamische Navigation verknüpft sind.

Die Struktur ist vollständig automatisierbar und basiert auf Hash-Validierung, JSON-gesteuerter Navigation und systemnaher Erweiterbarkeit.

.SH FILES
.TP
.I index.html
Startseite des Moduls
.TP
.I subsite-1/index.html ... subsite-9/index.html
Verschachtelte Unterseiten
.TP
.I navigation.json
Automatisch generierte Menüstruktur
.TP
.I block-box.json
Hash-Datenbank aller Pfade

.SH AUTHOR
J.K – QuantumReady / PRAI Infrastructure
